services:
  housedashboard:
    container_name: housedashboard_container
    image: house_dashboard:0.4
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - type: bind
        source: /mnt/md0/sambashare1tb/housedashboard/logs
        target: /usr/src/app/logs
      - type: bind
        source: /mnt/md0/sambashare1tb/housedashboard/config
        target: /usr/src/app/config