network:
  devices:
    google:
      address: 8.8.8.8
      type: 1
      rate: 2
    router:
      address: 192.168.0.1
      type: 1
      rate: 2
    local_dns:
      address: 192.168.0.9
      type: 1
      rate: 2
    pixel_6a:
      address: 192.168.0.125
      type: 2
      rate: 2
    galaxy_A90:
      address: 192.168.0.127
      type: 2
      rate: 2

  buffer_size: 1000

energy:
  devices:
    printer_plug:
      address: 192.168.0.49
      rate: 1

  buffer_size: 1000