hours_to_display: 2
hours_for_tables: 0.001

ping:
  devices:
    google:
      address: 8.8.8.8
      type: 1

power:
  devices:
    printer:
      address: 192.168.0.49
      type: 1

postgresql:
  ip: X.X.X.X
  port: YYYY
  user: very_nice_user
  password: great_password
  table_name: wonderful_db_name