network:
  devices:
    google:
      address: 8.8.8.8
      type: 1
      rate: 0.5
    router:
      address: 192.168.0.1
      type: 1
      rate: 0.5
    local_dns:
      address: 192.168.0.9
      type: 1
      rate: 0.5
    pixel_6a:
      address: 192.168.0.128
      type: 2
      rate: 0.5
    galaxy_A90:
      address: 192.168.0.127
      type: 2
      rate: 0.5

  buffer_size: 1000

energy:
  devices:
    printer_plug:
      address: 192.168.0.49
      rate: 0.2

  buffer_size: 10000